/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { KeyValue } from '../model/keyValue';
import { SalesReportRequestParams } from '../model/salesReportRequestParams';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SalesReportControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * getNoOfBills
     *
     * @param params params
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNoOfBillsUsingPOST(params: SalesReportRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Array<number>>;
    public getNoOfBillsUsingPOST(params: SalesReportRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<number>>>;
    public getNoOfBillsUsingPOST(params: SalesReportRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<number>>>;
    public getNoOfBillsUsingPOST(params: SalesReportRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (params === null || params === undefined) {
            throw new Error('Required parameter params was null or undefined when calling getNoOfBillsUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<number>>(`${this.basePath}/sales/getNoOfBills`,
            params,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getNoOfCustomers
     *
     * @param params params
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNoOfCustomersUsingPOST(params: SalesReportRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Array<number>>;
    public getNoOfCustomersUsingPOST(params: SalesReportRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<number>>>;
    public getNoOfCustomersUsingPOST(params: SalesReportRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<number>>>;
    public getNoOfCustomersUsingPOST(params: SalesReportRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (params === null || params === undefined) {
            throw new Error('Required parameter params was null or undefined when calling getNoOfCustomersUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<number>>(`${this.basePath}/sales/getNumberOfCustomers`,
            params,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getPax
     *
     * @param params params
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPaxUsingPOST(params: SalesReportRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Array<number>>;
    public getPaxUsingPOST(params: SalesReportRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<number>>>;
    public getPaxUsingPOST(params: SalesReportRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<number>>>;
    public getPaxUsingPOST(params: SalesReportRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (params === null || params === undefined) {
            throw new Error('Required parameter params was null or undefined when calling getPaxUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<number>>(`${this.basePath}/sales/getPax`,
            params,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getReport
     *
     * @param params params
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getReportUsingPOST(params: SalesReportRequestParams, observe?: 'body', reportProgress?: boolean): Observable<{ [key: string]: KeyValue; }>;
    public getReportUsingPOST(params: SalesReportRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<{ [key: string]: KeyValue; }>>;
    public getReportUsingPOST(params: SalesReportRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<{ [key: string]: KeyValue; }>>;
    public getReportUsingPOST(params: SalesReportRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (params === null || params === undefined) {
            throw new Error('Required parameter params was null or undefined when calling getReportUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<{ [key: string]: KeyValue; }>(`${this.basePath}/sales/getReport`,
            params,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
